language: php
php:
  - 7

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - phpunit --testsuite unit --coverage-clover=coverage.clover
  - phpunit --testsuite integration

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

# temporary
matrix:
  allow_failures:
    - php: hhvm
